export const cars = [
        {
            id: 1,
            image: 'assets/car1.avif',
            title: 'Benz',
            location: 'Lagos',
            price: 1700,
            condition: 'Air conditioning',
            passengers: 4,
        },
        {
            id: 2,
            image: 'assets/car2.avif',
            title: 'Ferari',
            location: 'Abuja',
            price: 1700,
            condition: 'Air conditioning',
            passengers: 4,
        },
        {
            id: 3,
            image: 'assets/car3.avif',
            title: 'Lamborghini',
            location: 'Ibadan',
            price: 1700,
            condition: 'Air conditioning',
            passengers: 4,
        },
        {
            id: 4,
            image: 'assets/car3.avif',
            title: 'Lamborghini',
            location: 'Lagos',
            price: 1700,
            condition: 'Air conditioning',
            passengers: 4,
        },
        {
            id: 5,
            image: 'assets/car3.avif',
            title: 'Lamborghini',
            location: 'Abuja',
            price: 1700,
            condition: 'Air conditioning',
            passengers: 4,
        },
        {
            id: 6,
            image: 'assets/car3.avif',
            title: 'Lamborghini',
            location: 'Ibadan',
            price: 1700,
            condition: 'Air conditioning',
            passengers: 4,
        },
        {
            id: 7,
            image: 'assets/car3.avif',
            title: 'Lamborghini',
            location: 'Lagos',
            price: 1700,
            condition: 'Air conditioning',
            passengers: 4,
        },
        {
            id: 8,
            image: 'assets/car3.avif',
            title: 'Lamborghini',
            location: 'Abuja',
            price: 1700,
            condition: 'Air conditioning',
            passengers: 4,
        },
        {
            id: 9,
            image: 'assets/car3.avif',
            title: 'Lamborghini',
            location: 'Ibadan',
            price: 1700,
            condition: 'Air conditioning',
            passengers: 4,
        },
        {
            id: 10,
            image: 'assets/car3.avif',
            title: 'Lamborghini',
            location: 'Lagos',
            price: 1700,
            condition: 'Air conditioning',
            passengers: 4,
        },
        {
            id: 11,
            image: 'assets/car3.avif',
            title: 'Lamborghini',
            location: 'Abuja',
            price: 1700,
            condition: 'Air conditioning',
            passengers: 4,
        },
        {
            id: 12,
            image: 'assets/car3.avif',
            title: 'Lamborghini',
            location: 'Ibadan',
            price: 1700,
            condition: 'Air conditioning',
            passengers: 4,
        },
        {
            id: 13,
            image: 'assets/car3.avif',
            title: 'Lamborghini',
            location: 'Lagos',
            price: 1700,
            condition: 'Air conditioning',
            passengers: 4,
        },
    ]

